In [4]:
from google.colab import files

uploaded = files.upload()

Saving preprocessed_main_df.csv to preprocessed_main_df.csv


In [11]:
import pandas as pd
import json
from transformers import BertTokenizer

In [5]:
df = pd.read_csv('preprocessed_main_df.csv')
df.head()

Unnamed: 0                                        User review Review date  \
0           0  ["\u0434\u043e\u0441\u0442\u043e\u0438\u043d\u...  2024-10-09   
1           1  ["\u0448\u0438\u043a\u0430\u0440\u043d\u0430\u...  2024-10-09   
2           2  ["\u0434\u043e\u0447\u043a\u0435", "\u043f\u04...  2024-10-09   
3           3  ["\u043f\u043e\u043a\u0430", "\u043d\u0435", "...  2024-10-09   
4           4  ["\u043e\u0442\u043b\u0438\u0447\u043d\u0430\u...  2024-10-09   

   Star review  Text length Has media  Has answer  Written by bot  
0            5           54         0           0               0  
1            5          195         0           0               0  
2            5           17         0           0               0  
3            5           33         0           0               0  
4            5           15         0           0               0

In [7]:
def get_tokens(review_json):
  try:
    decoded_reviews = json.loads(review_json)
    text = " ".join(decoded_reviews)
    tokens = text.split()
    return tokens
  except json.JSONDecodeError:
    return []

df['User review'] = df['User review'].apply(get_tokens)
df.head()

Unnamed: 0                                        User review Review date  \
0           0  [достоинства, все, устроило, нормальная, демис...  2024-10-09   
1           1  [шикарная, начиталась, отзывы, рискнула, что, ...  2024-10-09   
2           2                               [дочке, понравилась]  2024-10-09   
3           3               [пока, не, одевала, то, что, хотела]  2024-10-09   
4           4                                 [отличная, куртка]  2024-10-09   

   Star review  Text length Has media  Has answer  Written by bot  
0            5           54         0           0               0  
1            5          195         0           0               0  
2            5           17         0           0               0  
3            5           33         0           0               0  
4            5           15         0           0               0

In [12]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-uncased')


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.72M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

In [18]:
reviews = df['User review'].apply(lambda x: ' '.join(x)).tolist()
tokens = tokenizer(reviews, padding=True, truncation=True, return_tensors="tf")
print(tokens)
#print(reviews[0])

{'input_ids': <tf.Tensor: shape=(2416, 206), dtype=int32, numpy=
array([[  101, 10356, 33940, ...,     0,     0,     0],
       [  101, 65928, 50617, ...,     0,     0,     0],
       [  101, 10356, 20218, ...,     0,     0,     0],
       ...,
       [  101,   329, 14961, ...,     0,     0,     0],
       [  101, 10842, 45801, ...,     0,     0,     0],
       [  101, 16646, 51098, ...,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2416, 206), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2416, 206), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=in

In [19]:
df['input_ids'] = tokens['input_ids'].numpy().tolist()
df['attention_mask'] = tokens['attention_mask'].numpy().tolist()
df.head()

Unnamed: 0                                        User review Review date  \
0           0  [достоинства, все, устроило, нормальная, демис...  2024-10-09   
1           1  [шикарная, начиталась, отзывы, рискнула, что, ...  2024-10-09   
2           2                               [дочке, понравилась]  2024-10-09   
3           3               [пока, не, одевала, то, что, хотела]  2024-10-09   
4           4                                 [отличная, куртка]  2024-10-09   

   Star review  Text length Has media  Has answer  Written by bot  \
0            5           54         0           0               0   
1            5          195         0           0               0   
2            5           17         0           0               0   
3            5           33         0           0               0   
4            5           15         0           0               0   

                                           input_ids  \
0  [101, 10356, 33940, 12236, 12538, 12506, 325, ...   
1  [101, 65928, 50617, 11776, 10124, 87361, 19847...   
2  [101, 10356, 20218, 10291, 92545, 45027, 19847...   
3  [101, 39665, 10396, 10468, 94882, 10185, 11743...   
4  [101, 10360, 10798, 23544, 316, 26078, 29238, ...   

                                      attention_mask  
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...  
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...  
2  [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...  
3  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, ...  
4  [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...

In [21]:
df.to_csv('Bert_df.csv')
files.download('Bert_df.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>